### ISSUE TITLE
Error while trying to gen Hungarian dictionary. Results in Empty hu.trie File

### ISSUE THREAD

**Issue by qwadrox** [streetsidesoftware/cspell-dicts#2443]
I followed the steps outlined in the documentation to create a new dictionary for the Hungarian language. However, the generated dictionaries/hu/dict/hu.trie file is consistently empty.

Steps Taken:
I have tried cleaning the project.
I placed .aff file next to the .dic file
I've reinstalled all dependencies with pnpm 
Despite multiple attempts, the issue persists. Attached below is the complete console output for reference.

UPDATED:
```sh
~/Documents/GitHub/cspell-dicts$ pnpm create-dictionary

> cspell-dicts@17.0.4 create-dictionary /home/qwadrox/Documents/GitHub/cspell-dicts
> node ./generator-cspell-dicts/node_modules/yo/lib/cli.js cspell-dicts


     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │      Welcome to the      │
   `---------´   │  cspell-dicts generator! │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? The package directory name (en_US, medical-terms) hu
? Friendly Name ("US English", "Medical Terms") Hungarian
? Description Hungarian dictionary for cspell.
? Source File Name /home/qwadrox/Downloads/hu_HU.dic
? Language locale, example: "en,en-US" for English and English US, "fr" for French, or use "*" for programming language dictionaries. 
hu
? Programming languageID/filetype, i.e. "typescript", "php", "go", or "*" for any. *
? Store as Trie: Mainly used for natural language dictionaries to store their large sizes. Yes
? Compile Dictionary? Yes
/home/qwadrox/Downloads/hu_HU.dic
Creating Folder: hu
   create dictionaries/hu/package.json
   create dictionaries/hu/README.md
   create dictionaries/hu/CHANGELOG.md
   create dictionaries/hu/cspell-ext.json
   create dictionaries/hu/cspell.json
   create dictionaries/hu/LICENSE
   create dictionaries/hu/cspell-tools.config.yaml
   create dictionaries/hu/dict/README.md
   create dictionaries/hu/src/README.md
   create dictionaries/hu/src/hu_HU.aff
   create dictionaries/hu/src/hu_HU.dic
   create dictionaries/hu/dict/hu.trie
Version 8.7.0
Usage: pnpm [command] [flags]
       pnpm [ -h | --help | -v | --version ]

Manage your dependencies:
      add                  Installs a package and any packages that it depends on. By default, any new package is installed as a prod
                           dependency
      import               Generates a pnpm-lock.yaml from an npm package-lock.json (or npm-shrinkwrap.json) file
   i, install              Install all dependencies for a project
  it, install-test         Runs a pnpm install followed immediately by a pnpm test
  ln, link                 Connect the local project to another one
      prune                Removes extraneous packages
  rb, rebuild              Rebuild a package
  rm, remove               Removes packages from node_modules and from the project's package.json
      unlink               Unlinks a package. Like yarn unlink but pnpm re-installs the dependency after removing the external link
  up, update               Updates packages to their latest version based on the specified range

Review your dependencies:
      audit                Checks for known security issues with the installed packages
      licenses             Check licenses in consumed packages
  ls, list                 Print all the versions of packages that are installed, as well as their dependencies, in a tree-structure
      outdated             Check for outdated packages

Run your scripts:
      exec                 Executes a shell command in scope of a project
      run                  Runs a defined package script
      start                Runs an arbitrary command specified in the package's "start" property of its "scripts" object
   t, test                 Runs a package's "test" script, if one was provided

Other:
      pack
      publish              Publishes a package to the registry
      root

Manage your store:
      store add            Adds new packages to the pnpm store directly. Does not modify any projects or files outside the store
      store path           Prints the path to the active store directory
      store prune          Removes unreferenced (extraneous, orphan) packages from the store
      store status         Checks for modified packages in the store

Options:
  -r, --recursive          Run the command for each project in the workspace.
✖ An error occured while running cspell-dicts:app#install
Error cspell-dicts 

Command failed with exit code 1: pnpm
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Jason3S** [comment]
@qwadrox,

There should have been a `hu.aff` file to go with the `hu.dic` file. Without that, it cannot generate words from the hunspell dictionary.

**Comment by qwadrox** [comment]
@Jason3S 
Indeed, My previous comment was my last attempt, and i forgot to place the .aff next to it. But I have multiple dic sources and none of them were working. Generator copied the files as needed. Please see my updated post to verify.

**Comment by qwadrox** [comment]
@Jason3S **Its going**

After a few hours of generation a new error arise: 
```sh
2023-08-31T09:23:11.690Z Progress: Words Processed - 282,900,000
2023-08-31T09:23:13.842Z Progress: Words Processed - 283,000,000
2023-08-31T09:23:19.483Z Progress: Words Processed - 283,100,000
2023-08-31T09:23:21.722Z Progress: Words Processed - 283,200,000
2023-08-31T09:23:23.918Z Progress: Words Processed - 283,300,000
2023-08-31T09:23:27.870Z Progress: Words Processed - 283,400,000
2023-08-31T09:23:27.907Z Done processing src/hu_HU.dic
2023-08-31T09:23:27.963Z Reduce duplicate word endings
RangeError: Set maximum size exceeded
    at Set.add (<anonymous>)
    at walk (file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:141:18)
    at file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:135:27
    at Array.reduce (<anonymous>)
    at walk (file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:132:36)
    at file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:135:27
    at Array.reduce (<anonymous>)
    at walk (file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:132:36)
    at file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:135:27
    at Array.reduce (<anonymous>)
 ELIFECYCLE  Command failed with exit code 1.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
✖ An error occured while running cspell-dicts:app#end
Error cspell-dicts
```
_Steps taken:
-Pulled changes from origin
-pnpm prune
-pnpm i_

**Comment by Jason3S** [comment]
@qwadrox,

That can happen if the Hunspell dictionary definition is recursive.

Please add the following to the bottom of the `cspell-tools.config.yaml` file:

```yaml
maxDepth: 0
checksumFile: true
```

It should generate much faster, but will be missing words. Increasing `maxDepth` to 1 or 2 might work.

**Comment by qwadrox** [comment]
My settings: 
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "hu-hu"
    sources:
      - filename: "src/hu_HU.dic"
        maxDepth: 1 # This is set to 1 to prevent initial builds from taking too long.
    format: "trie3"
    targetDirectory: "./dict"
    generateNonStrict: true
    compress: false
maxDepth: 0
checksumFile: true
```
But the result eventually same:

```sh
2023-08-31T12:39:47.824Z Progress: Words Processed - 283,300,000
2023-08-31T12:39:51.554Z Progress: Words Processed - 283,400,000
2023-08-31T12:39:51.595Z Done processing src/hu_HU.dic
2023-08-31T12:39:51.657Z Reduce duplicate word endings
RangeError: Set maximum size exceeded
    at Set.add (<anonymous>)
    at walk (file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:141:18)
    at file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:135:27
    at Array.reduce (<anonymous>)
    at walk (file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:132:36)
    at file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:135:27
    at Array.reduce (<anonymous>)
    at walk (file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:132:36)
    at file:///home/qwadrox/Documents/GitHub/cspell-dicts/node_modules/.pnpm/cspell-trie-lib@7.0.0/node_modules/cspell-trie-lib/dist/lib/TrieNode/trie-util.js:135:27
    at Array.reduce (<anonymous>)
 ELIFECYCLE  Command failed with exit code 1.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
```
Do you have an idea by any chance what should i try? Thank you. @Jason3S

**Comment by Jason3S** [comment]
@qwadrox,

Please trying:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: "hu-hu"
    sources:
      - filename: "src/hu_HU.dic"
        maxDepth: 0 # This is set to 0 to prevent initial builds from taking too long.
    format: "trie3"
    targetDirectory: "./dict"
    generateNonStrict: true
    compress: false
checksumFile: true
```

**Comment by qwadrox** [comment]
this time it was 3 sec :D should it be like that? 
```sh
~/Documents/GitHub/cspell-dicts/dictionaries/hu_HU$ pnpm run build

> @cspell/dict-hu-hu@1.0.0 build /home/qwadrox/Documents/GitHub/cspell-dicts/dictionaries/hu_HU
> cross-env NODE_OPTIONS=--max_old_space_size=8192 cspell-tools-cli build

2023-08-31T17:21:14.367Z Start compile: hu-hu
2023-08-31T17:21:14.369Z Reading hu_HU.dic
2023-08-31T17:21:14.534Z Done reading hu_HU.dic
2023-08-31T17:21:14.535Z Reading Words into Trie
2023-08-31T17:21:14.536Z Process "src/hu_HU.dic" to "dict/hu-hu.trie"
2023-08-31T17:21:16.103Z Progress: Words Processed - 100,000
2023-08-31T17:21:17.800Z Done processing src/hu_HU.dic
2023-08-31T17:21:17.831Z Reduce duplicate word endings
2023-08-31T17:21:18.625Z Writing to file hu-hu.trie
2023-08-31T17:21:19.097Z Done writing to file hu-hu.trie
2023-08-31T17:21:19.097Z Done "dict/hu-hu.trie"
2023-08-31T17:21:19.097Z Done compile: hu-hu
2023-08-31T17:21:19.097Z Update checksum: /home/qwadrox/Documents/GitHub/cspell-dicts/dictionaries/hu_HU/checksum.txt
2023-08-31T17:21:19.104Z Complete.
```

**Comment by Jason3S** [comment]
@qwadrox,

It was fast because it didn't apply all the rules to generate the words. Looks like Hungarian 
is like Hebrew and Basque. There needs to be some tool work done to fully support these languages, they have many very complex rules that can be recursive.

But, I haven't had the time to look into it.

**Comment by qwadrox** [comment]
I understand.
