### ISSUE TITLE
French misspelling not detected

### ISSUE THREAD

**Issue by inwardmovement** [streetsidesoftware/cspell-dicts#92]
I have the word `amitité` (misspell of "amitié") which is not detected. I don't have it in my user words so it should be flagged as misspelling. 

It is not in the [words list](https://raw.githubusercontent.com/streetsidesoftware/cspell-dicts/master/packages/fr_FR/French.dic) so it may have something to do with something else?

**Comment by Jason3S** [comment]
It must be something else. `amitité` doesn't exist in any of the dictionaries.

What kind of file is it? Markdown or LaTex?

**Comment by inwardmovement** [comment]
Markdown.
I suspect there is a kind of (long) delay when detecting words, which may come from something else than the extension.

**Comment by Jason3S** [comment]
There might be something wrong with a regular expression. What kind of files are you checking?

**Comment by inwardmovement** [comment]
It's a simple markdown file.

**Comment by Jason3S** [comment]
@inwardmovement if you install `cspell`, there is the `check` command that will display the file you are checking in color. It is possible that the surrounding text is being ignored.

**Comment by inwardmovement** [comment]
The check doesn't work:
```
> cspell check "test.md"
Check file: test.md

Failed to read "test.md"
```

When I start VSCode, the initialization of the cspell extension outputs this in the log:
```
Failed to read "c:\...\cspell-dicts\packages\fr_FR_90\cspell-ext.json": Error: ENOENT: no such file or directory, open 'c:\...\cspell-dicts\packages\fr_FR_90\cspell-ext.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at readJsonFile (c:\...\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.2\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:24:30)
    at importSettings (c:\...\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.2\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:58:93)
    at c:\...\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.2\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:43:22
    at Array.map (<anonymous>)
    at normalizeSettings (c:\...\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.2\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:43:10)
    at Object.getGlobalSettings (c:\...\.vscode\extensions\streetsidesoftware.code-spell-checker-1.9.2\server\node_modules\cspell-lib\dist\Settings\CSpellSettingsServer.js:191:65) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'c:\\Users\\...\\cspell-dicts\\packages\\fr_FR_90\\cspell-ext.json'
}
```
